name: jaspr_bloc
description: Jaspr components that make it easy to implement the BLoC (Business
  Logic Component) design pattern. Built to be used with the bloc state
  management package.
version: 0.0.1
repository: https://github.com/f-person/jaspr_bloc
issue_tracker: https://github.com/f-person/jaspr_bloc
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.0.2
  jaspr: ^0.13.2
  jaspr_provider: # ^0.0.3
    git:
      url: https://github.com/jWinterDay/jaspr_provider.git

# dev_dependencies:
#   jaspr_test: ^0.1.0
